[/]
  /var/lib/copyparty-jail
  accs:
    r: *    # everyone can [r]ead  (browse/download)


# above is a very simple config;
# the webroot is /var/lib/copyparty-jail
# readable by everyone, no login required
#
# you'll want to replace this file; some inspiration:
# a basic example: https://github.com/9001/copyparty/blob/hovudstraum/contrib/systemd/copyparty.example.conf
# another example: https://github.com/9001/copyparty/blob/hovudstraum/docs/example.conf
# CTRL-F "config file example" here: https://github.com/9001/copyparty
# full list of options: https://copyparty.eu/cli/
