"use strict";


// the three-letter name of the language you're translating to
var my_lang = "vie";


////////////////////////////////////////////////////////////////////////
// please ignore the next 5 lines:
var Ls={}, SR='', wah='';
function langmod() {
	if (window.LANGN)
		LANGN.push([my_lang, Ls[my_lang].tt]);
}


////////////////////////////////////////////////////////////////////////
// alright,
// below this point is where the actual translation happens;
// here is the pairs of "text-identifier": "text-to-translate"
//
// you do not need to translate the TLNotes, those are just for you :-)
//
// when you are happy with this translation and want to submit it,
// copy the text below into a new file in the translations folder;
// https://github.com/9001/copyparty/tree/hovudstraum/copyparty/web/tl

/*

TLNotes:
- navpane: thanh điều hướng
- breadcrumb: đường dẫn


*/


Ls.vie = {
	"tt": "Tiếng Việt",

	"cols": {
		"c": "nút hành động",
		"dur": "thời lượng",
		"q": "chất lượng / bitrate",
		"Ac": "codec âm thanh",
		"Vc": "codec video",
		"Fmt": "định dạng / container",
		"Ahash": "checksum âm thanh",
		"Vhash": "checksum video",
		"Res": "độ phân giải",
		"T": "loại tệp",
		"aq": "chất lượng âm thanh / bitrate",
		"vq": "chất lượng video / bitrate",
		"pixfmt": "subsampling / pixel structure",
		"resw": "độ phân giải ngang",
		"resh": "độ phân giải dọc",
		"chs": "kênh âm thanh",
		"hz": "tốc độ lấy mẫu",
	},

	"hks": [
		[
			"misc",
			["ESC", "đóng nhiều mục"],

			"file-manager",
			["G", "chuyển đổi chế độ xem danh sách / lưới"],
			["T", "chuyển đổi ảnh thu nhỏ / biểu tượng"],
			["⇧ A/D", "kích thước ảnh thu nhỏ"],
			["ctrl-K", "xoá mục đã chọn"],
			["ctrl-X", "cắt mục đã chọn vào bảng nhớ tạm"],
			["ctrl-C", "sao chép mục đã chọn vào bảng nhớ tạm"],
			["ctrl-V", "dán (di chuyển/sao chép) tại đây"],
			["Y", "tải xuống mục đã chọn"],
			["F2", "đổi tên mục đã chọn"],

			"file-list-sel",
			["space", "chuyển đổi chọn tệp"],
			["↑/↓", "di chuyển con trỏ chọn"],
			["ctrl ↑/↓", "di chuyển con trỏ và khung nhìn"],
			["⇧ ↑/↓", "chọn tệp trước / sau"],
			["ctrl-A", "chọn tất cả tệp / thư mục"],
		], [
			"navigation",
			["B", "chuyển đổi đường dẫn / thanh điều hướng"],
			["I/K", "thư mục trước / sau"],
			["M", "thư mục cha (hoặc thu gọn hiện tại)"],
			["V", "chuyển đổi thư mục / tệp văn bản trong thanh điều hướng"],
			["A/D", "kích thước thanh điều hướng"],
		], [
			"audio-player",
			["J/L", "bài trước / sau"],
			["U/O", "lùi / tiến 10 giây"],
			["0..9", "nhảy đến 0%..90%"],
			["P", "phát/tạm dừng (cũng khởi động)"],
			["S", "chọn bài đang phát"],
			["Y", "tải xuống bài hát"],
		], [
			"image-viewer",
			["J/L, ←/→", "ảnh trước / sau"],
			["Home/End", "ảnh đầu / cuối"],
			["F", "toàn màn hình"],
			["R", "xoay theo chiều kim đồng hồ"],
			["⇧ R", "xoay ngược chiều kim đồng hồ"],
			["S", "chọn ảnh"],
			["Y", "tải xuống ảnh"],
		], [
			"video-player",
			["U/O", "lùi / tiến 10 giây"],
			["P/K/Space", "phát/tạm dừng"],
			["C", "tiếp tục phát bài tiếp theo"],
			["V", "vòng lặp"],
			["M", "tắt tiếng"],
			["[ and ]", "đặt khoảng lặp"],
		], [
			"textfile-viewer",
			["I/K", "tệp trước / sau"],
			["M", "đóng tệp văn bản"],
			["E", "chỉnh sửa tệp văn bản"],
			["S", "chọn tệp (để cắt/sao chép/đổi tên)"],
		]
	],

	"m_ok": "OK",
	"m_ng": "Hủy",

	"enable": "Bật",
	"danger": "NGUY HIỂM",
	"clipped": "đã sao chép vào bảng nhớ tạm",

	"ht_s1": "giây",
	"ht_s2": "giây",
	"ht_m1": "phút",
	"ht_m2": "phút",
	"ht_h1": "giờ",
	"ht_h2": "giờ",
	"ht_d1": "ngày",
	"ht_d2": "ngày",
	"ht_and": " và ",

	"goh": "bảng điều khiển",
	"gop": 'thư mục trước">trước',
	"gou": 'thư mục cha">lên',
	"gon": 'thư mục sau">tiếp',
	"logout": "Đăng xuất ",
	"login": "Đăng nhập",
	"access": "quyền truy cập",
	"ot_close": "đóng menu con",

	"ot_search": "tìm kiếm các tệp theo thuộc tính, đường dẫn / tên, tag nhạc hoặc bất kỳ sự kết hợp nào của chúng$N$N&lt;code&gt;foo bar&lt;/code&gt; = phải chứa cả «foo» và «bar»,$N&lt;code&gt;foo -bar&lt;/code&gt; = phải chứa «foo» nhưng không chứa «bar»,$N&lt;code&gt;^yana .opus$&lt;/code&gt; = bắt đầu bằng «yana» và là tệp «opus»$N&lt;code&gt;&quot;try unite&quot;&lt;/code&gt; = chứa chính xác «try unite»$N$Nđịnh dạng ngày là iso-8601, như$N&lt;code&gt;2009-12-31&lt;/code&gt; hoặc &lt;code&gt;2020-09-12 23:30:00&lt;/code&gt;",


	"ot_unpost": "unpost: xoá các tệp đã tải lên gần đây hoặc huỷ những tệp đang tải dở",
	"ot_bup": "bup: trình tải lên cơ bản, hỗ trợ cả Netscape 4.0",
	"ot_mkdir": "mkdir: tạo thư mục mới",
	"ot_md": "new-file: tạo tệp văn bản mới",
	"ot_msg": "msg: gửi tin nhắn đến nhật ký máy chủ",
	"ot_mp": "tuỳ chọn trình phát phương tiện",
	"ot_cfg": "tuỳ chọn cấu hình",
	"ot_u2i": 'up2k: tải tệp lên (nếu bạn có quyền ghi) hoặc chuyển sang chế độ tìm kiếm để xem chúng có tồn tại ở đâu đó trên máy chủ không$N$Ntải lên có thế tiếp tục nếu bị gián đoạn, chạy đa luồng và giữ nguyên dấu thời gian tệp, nhưng tiêu tốn nhiều CPU hơn [🎈]&nbsp; (trình tải lên cơ bản)<br /><br />trong quá trình tải, biểu tượng này sẽ trở thành chỉ thị tiến trình!',
	"ot_u2w": 'up2k: tải tệp lên với hỗ trợ tiếp tục (đóng trình duyệt và thả lại tệp đó lên sau)$N$Nchạy đa luồng và giữ nguyên dấu thời gian tệp, nhưng tiêu tốn nhiều CPU hơn [🎈]&nbsp; (trình tải lên cơ bản)<br /><br />trong quá trình tải, biểu tượng này sẽ trở thành chỉ thị tiến trình!',
	"ot_noie": 'Vui lòng sử dụng Chrome / Firefox / Edge',

	"ab_mkdir": "tạo thư mục",
	"ab_mkdoc": "tạo tệp văn bản",
	"ab_msg": "gửi tin nhắn đến nhật ký máy chủ",

	"ay_path": "bỏ qua đến thư mục",
	"ay_files": "bỏ qua đến tệp",

	"wt_ren": "đổi tên các mục đã chọn$NPhím tắt: F2",
	"wt_del": "xóa các mục đã chọn$NPhím tắt: ctrl-K",
	"wt_cut": "cắt các mục đã chọn &lt;small&gt;(sau đó dán ở nơi khác)&lt;/small&gt;$NPhím tắt: ctrl-X",
	"wt_cpy": "sao chép các mục đã chọn vào bảng nhớ tạm$N(để dán ở nơi khác)$NPhím tắt: ctrl-C",
	"wt_pst": "dán một lựa chọn đã cắt / sao chép trước đó$NPhím tắt: ctrl-V",
	"wt_selall": "chọn tất cả các tệp$NPhím tắt: ctrl-A (khi tệp được chọn)",
	"wt_selinv": "đảo ngược lựa chọn",
	"wt_zip1": "tải thư mục này dưới định dạng nén",
	"wt_selzip": "tải lựa chọn dưới định dạng nén",
	"wt_seldl": "tải lựa chọn dưới dạng các tệp riêng biệt$NPhím tắt: Y",
	"wt_npirc": "sao chép thông tin bản nhạc theo định dạng irc",
	"wt_nptxt": "sao chép thông tin bản nhạc dưới dạng văn bản thuần túy",
	"wt_m3ua": "thêm vào danh sách phát m3u (bấm <code>📻copy</code> sau)",
	"wt_m3uc": "sao chép danh sách phát m3u vào bảng nhớ tạm",
	"wt_grid": "chuyển đổi chế độ xem danh sách / lưới $NPhím tắt: G",
	"wt_prev": "bài trước$NPhím tắt: J",
	"wt_play": "phát / tạm dừng$NPhím tắt: P",
	"wt_next": "bài sau$NPhím tắt: L",

	"ul_par": "tải lên song song:",
	"ut_rand": "ngẫu nhiên hoá tên tệp",
	"ut_u2ts": "sao chép dấu thời gian chỉnh sửa cuối$Ntừ hệ thống tệp của bạn lên máy chủ\">📅",
	"ut_ow": "ghi đè các tệp đã có trên máy chủ?$N🛡️: không bao giờ (sẽ tạo tên tệp mới)$N🕒: ghi đè nếu tệp trên máy chủ cũ hơn$N♻️: luôn ghi đè nếu hai tệp khác nhau",
	"ut_mt": "tiếp tục băm các tệp khác trong khi tải lên$N$NCó thể tắt nếu CPU hoặc HDD của bạn bị nghẽn",
	"ut_ask": 'yêu cầu xác nhận trước khi bắt đầu tải lên">💭',
	"ut_pot": "cải thiện tốc độ tải lên trên các thiết bị chậm$Nbằng cách đơn giản hoá giao diện người dùng",
	"ut_srch": "không tải lên, chỉ kiểm tra xem tệp$Nđã tồn tại trên máy chủ hay chưa (sẽ quét toàn bộ thư mục bạn có quyền đọc)",
	"ut_par": "tạm dừng tải lên bằng cách đặt thành 0$N$NTăng lên nếu kết nối chậm hoặc độ trễ cao$N$NGiữ ở mức 1 khi dùng LAN hoặc nếu ổ cứng máy chủ bị nghẽn",
	"ul_btn": "thả tệp / thư mục<br>ở đây (hoặc nhấn vào tôi)",
	"ul_btnu": "T Ả I  L Ê N",
	"ul_btns": "T Ì M  K I Ế M",

	"ul_hash": "băm",
	"ul_send": "gửi",
	"ul_done": "hoàn tất",
	"ul_idle1": "chưa có mục nào trong hàng chờ tải lên",
	"ut_etah": "tốc độ &lt;em&gt;băm&lt;/em&gt; trung bình và thời gian dự kiến để hoàn tất",
	"ut_etau": "tốc độ &lt;em&gt;tải lên&lt;/em&gt; trung bình và thời gian dự kiến để hoàn tất",
	"ut_etat": "tốc độ &lt;em&gt;tổng&lt;/em&gt; trung bình và thời gian dự kiến để hoàn tất",

	"uct_ok": "hoàn tất thành công",
	"uct_ng": "không hợp lệ: lỗi / bị từ chối / không tìm thấy",
	"uct_done": "đã xử lý: gồm cả thành công và không hợp lệ",
	"uct_bz": "đang băm hoặc tải lên",
	"uct_q": "nhàn rỗi, đang chờ",

	"utl_name": "tên tệp",
	"utl_ulist": "danh sách",
	"utl_ucopy": "sao chép",
	"utl_links": "đường dẫn",
	"utl_stat": "trạng thái",
	"utl_prog": "tiến trình",

	// keep short:

	// phần up2k
	"utl_404": "404",
	"utl_err": "LỖI",
	"utl_oserr": "Lỗi hệ thống",
	"utl_found": "tìm thấy",
	"utl_defer": "hoãn",
	"utl_yolo": "YOLO",
	"utl_done": "hoàn tất",

	"udt_up": "Tải lên",
	"udt_srch": "Tìm kiếm",
	"udt_drop": "thả vào đây",

	"udt_up": "Tải lên",
	"udt_srch": "Tìm kiếm",
	"udt_drop": "thả vào đây",

	"u_nav_m": '<h6>chọn phương thức tải lên</h6><code>Enter</code> = Tệp (một hoặc nhiều)\n<code>ESC</code> = Một thư mục (kèm thư mục con)',
	"u_nav_b": '<a href="#" id="modal-ok">Tệp</a><a href="#" id="modal-ng">Một thư mục</a>',

	// settings / config:
	"cl_opts": "tuỳ chọn",
	"cl_hfsz": "kích thước tệp",
	"cl_themes": "giao diện",
	"cl_langs": "ngôn ngữ",
	"cl_ziptype": "định dạng nén",
	"cl_uopts": "tuỳ chọn up2k",
	"cl_favico": "favicon",
	"cl_bigdir": "thư mục lớn",
	"cl_hsort": "#sắp xếp",
	"cl_keytype": "ghi chú bàn phím",
	"cl_hiddenc": "cột đã ẩn",
	"cl_hidec": "ẩn",
	"cl_reset": "đặt lại",
	"cl_hpick": "chạm vào tiêu đề cột để ẩn trong bảng bên dưới",
	"cl_hcancel": "đã hủy việc ẩn cột",

	// settings / tuỳ chọn
	"ct_grid": '田 chế độ lưới',
	"ct_ttips": '༼ ◕_◕ ༽">ℹ️ tooltips',
	"ct_thumb": 'ở chế độ lưới, chuyển biểu tượng hoặc hình thu nhỏ$NPhím tắt: T">🖼️ ảnh thu nhỏ',
	"ct_csel": 'dùng CTRL và SHIFT để chọn tệp trong chế độ lưới">sel',
	"ct_ihop": 'khi đóng trình xem ảnh, cuộn xuống tệp đã xem gần nhất">g⮯',
	"ct_dots": 'hiển thị tệp ẩn (nếu máy chủ cho phép)">dotfiles',
	"ct_qdel": 'khi xóa tệp, chỉ hỏi xác nhận một lần">qdel',
	"ct_dir1st": 'sắp xếp thư mục trước tệp">📁 first',
	"ct_nsort": 'sắp xếp tự nhiên (cho tên tệp có số ở đầu)">nsort',
	"ct_utc": 'hiển thị mọi thời gian theo UTC">UTC',
	"ct_readme": 'hiển thị README.md trong danh sách thư mục">📜 readme',
	"ct_idxh": 'hiển thị index.html thay cho danh sách thư mục">htm',
	"ct_sbars": 'hiển thị thanh cuộn">⟊',

	// tuỳ chọn up2k
	"cut_umod": "nếu tệp đã tồn tại trên máy chủ, cập nhật dấu thời gian chỉnh sửa cuối của máy chủ cho khớp với tệp cục bộ của bạn (yêu cầu quyền ghi và xóa)\">re📅",

	"cut_turbo": "nút YOLO, bạn gần như KHÔNG nên bật tuỳ chọn này:$N$Ndùng khi bạn đang tải lên một lượng tệp rất lớn và phải khởi động lại vì lý do nào đó, và muốn tiếp tục tải càng sớm sàng tốt$N$Ntuỳ chọn này thay thế kiểm tra băm bằng kiểm tra <em>&quot;kích thước tệp ở trên máy chủ có giống nhau không&quot;</em> nên nếu nội dung tệp khác nhau thì sẽ KHÔNG được tải lên$N$Nbạn nên tắt tuỳ chọn này sau khi tải lên xong, và &quot;tải lên&quot; lại các tệp đó để xác minh\">turbo",

	"cut_datechk": "không có tác dụng trừ khi nút turbo được bật$N$Ngiảm mức độ yolo một chút; kiểm tra xem dấu thời gian tệp trên máy chủ có khớp với của bạn không$N$Nnên <em>về lý thuyết</em> có thể phát hiện phần lớn tệp chưa xong hoặc bị lỗi, nhưng không thể thay thế cho việc chạy xác minh sau khi tắt turbo\">date-chk",

	"cut_u2sz": "kích thước (tính theo MiB) của mỗi khối tải lên; dùng kích thước khối lớn khi truyền ở khoảng cách lục địa. Hãy thử giá trị nhỏ hơn với kết nối không ổn định",

	"cut_flag": "đảm bảo chỉ một tab được tải lên tại một thời điểm $N -- tab khác cũng cần bật tùy chọn này $N -- tác dụng trong các tab cùng tên miền",

	"cut_az": "tải tệp theo thứ tự bảng chữ cái thay vì tệp nhỏ trước$N$Ntải lên theo thứ tự bảng chữ cái giúp dễ quan sát nếu có vấn đề trên máy chủ, nhưng làm tốc độ tải chậm hơn trên mạng cáp quang hoặc LAN",

	"cut_nag": "thông báo của hệ điều hành khi tải lên hoàn tất$N(chỉ khi trình duyệt hoặc tab không hoạt động)",
	"cut_sfx": "âm báo khi tải lên hoàn tất$N(chỉ khi trình duyệt hoặc tab không hoạt động)",

	"cut_mt": "dùng đa luồng để tăng tốc băm tệp$N$dùng web workers và cần $nhiều RAM hơn (tối đa thêm 512 MiB)$N$làm cho https nhanh hơn 30%, http nhanh hơn 4.5 lần\">mt",

	"cut_wasm": "dùng wasm thay vì bộ băm tích hợp của trình duyệt; nhanh hơn trên trình duyệt chromium nhưng làm tăng tải CPU, và nhiều bản chrome cũ có lỗi khiến trình duyệt dùng hết RAM và treo nếu bật tuỳ chọn này\">wasm",

	// favicon
	"cft_text": "chuỗi favicon (để trống và làm mới trang để tắt)",
	"cft_fg": "màu chữ",
	"cft_bg": "màu nền",

	// big dirs
	"cdt_lim": "số tệp tối đa hiển thị trong thư mục",
	"cdt_ask": "khi cuộn xuống cuối,$Nthay vì tải thêm tệp,$Nhỏi người dùng muốn làm gì",
	"cdt_hsort": "số lượng luật sắp xếp(&lt;code&gt;,sorthref&lt;/code&gt;) được đưa vào URL media. Đặt bằng 0 cũng sẽ bỏ qua các quy tắc sắp xếp trong liên kết media khi nhấp vào chúng",

	"tt_entree": "hiển thị thanh điều hướng (cây thư mục)$NPhím tắt: B",
	"tt_detree": "hiển thị đường dẫn$NPhím tắt: B",
	"tt_visdir": "cuộn đến thư mục đã chọn",
	"tt_ftree": "chuyển đổi cây thư mục / tệp văn bản$NPhím tắt: V",
	"tt_pdock": "hiển thị thư mục cha trong thanh ghim trên cùng",
	"tt_dynt": "tự mở rộng khi cây mở rộng",
	"tt_wrap": "ngắt dòng",
	"tt_hover": "hiện thị dòng tràn khi rê chuột$N( không cuộn được nếu $N&nbsp; con trỏ chuột nằm ngoài cột trái )",

	"ml_pmode": "ở cuối thư mục...",
	"ml_btns": "lệnh",
	"ml_tcode": "mã hoá lại",
	// chắc là phần nhạc
	"ml_tcode2": "mã hoá lại thành",
	"ml_tint": "tô màu",
	"ml_eq": "bộ cân bằng âm thanh",
	"ml_drc": "bộ nén dải động",

	// nhạc

	"mt_loop": "lặp lại một bài\">🔁",
	"mt_one": "dừng sau một bài\">1️⃣",
	"mt_shuf": "trộn các bài trong thư mụcr\">🔀",
	"mt_aplay": "tự động phát nếu có ID bài trong link bạn nhấp để truy cập máy chủ$N$Ntắt tuỳ chọn sẽ ngăn URL của trang cập nhật theo ID bài khi phát nhạc, tránh tự động phát nếu cài đặt mất nhưng URL còn\">a▶",
	"mt_preload": "bắt đầu tải bài hát tiếp theo khi gần hết bài để phát liền mạch\">preload",
	"mt_prescan": "chuyển đến thư mục tiếp theo trước khi bài cuối cùng $Nkết thúc, giúp giữ trình duyệt hoạt động $N và không dừng phát nhạc\">nav",
	"mt_fullpre": "cố gắng tải trước toàn bộ bài;$N✅ bật với kết nối <b>không ổn định</b>,$N❌ tắt <b>với kết nối chậm</b>\">full",
	"mt_fau": "trên điện thoại, ngăn nhạc dừng nếu bài tiếp theo tải chậm (có thể gây lỗi hiển thị tag nhạc)\">☕️",
	"mt_waves": "thanh tiến trình bài hát dạng sóng:$Nhiển thị biên độ âm thanh trong thanh tiến trình\">~s",
	"mt_npclip": "hiển thị nút để sao chép bài đang phát\">/np",
	"mt_m3u_c": "hiển thị nút để sao chép $Nnhững bài đã chọn dưới dạng danh sách phát m3u8\">📻",
	"mt_octl": "tích hợp hệ điều hành (phím tắt media / OSD)\">os-ctl",
	"mt_oseek": "cho phép tìm kiếm qua tích hợp hệ điều hành$N$Nlưu ý: trên một số thiết bị (iphone), $Nthao tác này sẽ thay thế nút bài hát tiếp theo\">seek",
	"mt_oscv": "hiển thị bài album trên OSD\">art",
	"mt_follow": "giữ bài đang phát trong tầm nhìn\">🎯",
	"mt_compact": "giao diện điều khiển thu gọn\">⟎",
	"mt_uncache": "xoá bộ nhớ đệm &nbsp;(thử nếu trình duyệt lưu trữ đệm $Nmột bản nhạc bị lỗi và không thể phát)\">uncache",
	"mt_mloop": "lặp trong thư mục đang mở\">🔁 loop",
	"mt_mnext": "tải thư mục tiếp theo và tiếp tục\">📂 next",
	"mt_mstop": "dừng phát\">⏸ stop",
	"mt_cflac": "chuyển flac / wav sang {0}\">flac",
	"mt_caac": "chuyển aac / m4a sang {0}\">aac",
	"mt_coth": "chuyển mọi loại khác (trừ mp3) thành {0}\">oth",
	"mt_c2opus": "lựa chọn tốt nhất cho máy tính, laptop, android\">opus",
	"mt_c2owa": "opus-weba, cho iOS 17.5 trở lên\">owa",
	"mt_c2caf": "opus-caf, cho iOS 11 đến 17\">caf",
	"mt_c2mp3": "dùng trên thiết bị cũ\">mp3",
	"mt_c2flac": "chất lượng âm thanh tốt nhất, nhưng tệp tải xuống lớn\">flac",
	"mt_c2wav": "phát không nén (tệp còn lớn hơn nữa)\">wav",
	"mt_c2ok": "lựa chọn hợp lý",
	"mt_c2nd": "không phải định dạng khuyến nghị cho thiết bị, nhưng hãy thử nếu bạn muốn",
	"mt_c2ng": "thiết bị dường như không hỗ trợ định dạng này, nhưng hãy thử nếu bạn muốn",
	"mt_xowa": "có một vài lỗi trên iOS ngăn phát nền với định dạng này; vui lòng dùng caf hoặc mp3",
	"mt_tint": "mức nền (0-100) trên thanh tiến trình",
	
	"mt_eq": "bật bộ cân bằng âm thanh và bộ tăng ích;$N$Nboost &lt;code&gt;0 &nbsp;&lt;/code&gt; = âm lượng chuẩn 100% (không chỉnh)$N$Nwidth &lt;code&gt;1 &nbsp;&lt;/code&gt; = stereo chuẩn (không chỉnh)$Nwidth &lt;code&gt;0.5&lt;/code&gt; = 50% pha trái-phải$Nwidth &lt;code&gt;0 &nbsp;&lt;/code&gt; = mono$N$Nboost &lt;code&gt;-0.8&lt;/code&gt; &amp; width &lt;code&gt;10&lt;/code&gt; = loại bỏ lời hát :^)$N$Nbật EQ giúp cho album được phát liền mạch không ngắt quãng, nên giữ các giá trị bằng 0 (trừ width = 1) nếu bạn không muốn thay đổi âm thanh gốc",

	"mt_drc": "bật bộ nén dải động (làm phẳng âm lượng / brickwaller); cũng bật EQ để cân bằng, nên đặt tất cả EQ trừ 'width' = 0 nếu không muốn$N$Ngiảm âm thanh trên THRESHOLD dB; với mỗi RATIO dB vượt THRESHOLD thì có 1 dB đầu ra, ví dụ tresh -24 và ratio 12 => âm lượng không vượt -22 dB, có thể tăng EQ boost lên 0.8 hoặc 1.8 với ATK 0 và RLS lớn 90 (chỉ Firefox; RLS max 1 trên browser khác)$N$NXem Wikipedia để hiểu chi tiết hơn",

	"mb_play": "phát",
	"mm_hashplay": "phát bản nhạc này?",
	"mm_m3u": "bấm <code>Enter/OK</code> để phát\nbấm <code>ESC/Cancel</code> để chỉnh sửa",
	"mp_breq": "cần firefox 82+ hoặc chrome 73+ hoặc iOS 15+",
	"mm_bload": "đang tải...",
	"mm_bconv": "đang chuyển đổi sang {0}, vui lòng chờ...",
	"mm_opusen": "trình duyệt không hỗ trợ tệp aac / m4a;\nchuyển sang định dạng opus hiện đã được bật",
	"mm_playerr": "phát lỗi: ",
	"mm_eabrt": "Việt phát nhạc đã bị huỷ",
	"mm_enet": "Kết nối Internet không ổn định",
	"mm_edec": "Tệp này dường như đã bị hỏng??",
	"mm_esupp": "Trình duyệt của bạn không nhận dạng được định dạng tệp này.",
	"mm_eunk": "Lỗi không xác định",
	"mm_e404": "Không thể phát âm thanh; lỗi 404: Không tìm thấy tệp.",
	"mm_e403": "Không thể phát âm thanh; lỗi 403: Từ chối truy cập.\n\nThử nhấn F5 để tải lại, có thể bạn đã đăng xuất",
	"mm_e500": "Không thể phát âm thanh; lỗi 500: Kiểm tra nhật ký máy chủ.",
	"mm_e5xx": "Không thể phát âm thanh; lỗi máy chủ ",
	"mm_nof": "không tìm thấy thêm tệp âm thanh nào gần đó",
	"mm_prescan": "Đang tìm bài nhạc tiếp theo để phát...",
	"mm_scank": "Đã tìm thấy bài nhạc tiếp theo:",
	"mm_uncache": "đã xoá bộ nhớ đệm; tất cả bài nhạc sẽ được tải lại khi phát tiếp",
	"mm_hnf": "bài nhạc này không còn tồn tại nữa",
	"im_hnf": "hình ảnh này không còn tồn tại nữa",

	"f_empty": 'this folder is empty',
	"f_chide": 'this will hide the column «{0}»\n\nyou can unhide columns in the settings tab',
	"f_bigtxt": "this file is {0} MiB large -- really view as text?",
	"f_bigtxt2": "view just the end of the file instead? this will also enable following/tailing, showing newly added lines of text in real time",
	"fbd_more": '<div id="blazy">showing <code>{0}</code> of <code>{1}</code> files; <a href="#" id="bd_more">show {2}</a> or <a href="#" id="bd_all">show all</a></div>',
	"fbd_all": '<div id="blazy">showing <code>{0}</code> of <code>{1}</code> files; <a href="#" id="bd_all">show all</a></div>',
	"f_anota": "only {0} of the {1} items were selected;\nto select the full folder, first scroll to the bottom",

	"f_dls": 'the file links in the current folder have\nbeen changed into download links',

	"f_partial": "To safely download a file which is currently being uploaded, please click the file which has the same filename, but without the <code>.PARTIAL</code> file extension. Please press CANCEL or Escape to do this.\n\nPressing OK / Enter will ignore this warning and continue downloading the <code>.PARTIAL</code> scratchfile instead, which will almost definitely give you corrupted data.",

	"ft_paste": "paste {0} items$NPhím tắt: ctrl-V",
	"fr_eperm": 'cannot rename:\nyou do not have “move” permission in this folder',
	"fd_eperm": 'cannot delete:\nyou do not have “delete” permission in this folder',
	"fc_eperm": 'cannot cut:\nyou do not have “move” permission in this folder',
	"fp_eperm": 'cannot paste:\nyou do not have “write” permission in this folder',
	"fr_emore": "select at least one item to rename",
	"fd_emore": "select at least one item to delete",
	"fc_emore": "select at least one item to cut",
	"fcp_emore": "select at least one item to copy to bảng nhớ tạm",

	"fs_sc": "share the folder you're in",
	"fs_ss": "share the selected files",
	"fs_just1d": "you cannot select more than one folder,\nor mix files and folders in one selection",
	"fs_abrt": "❌ abort",
	"fs_rand": "🎲 rand.name",
	"fs_go": "✅ create share",
	"fs_name": "name",
	"fs_src": "source",
	"fs_pwd": "passwd",
	"fs_exp": "expiry",
	"fs_tmin": "min",
	"fs_thrs": "hours",
	"fs_tdays": "days",
	"fs_never": "eternal",
	"fs_pname": "optional link name; will be random if blank",
	"fs_tsrc": "the file or folder to share",
	"fs_ppwd": "optional password",
	"fs_w8": "creating share...",
	"fs_ok": "press <code>Enter/OK</code> to bảng nhớ tạm\npress <code>ESC/Cancel</code> to Close",

	"frt_dec": "may fix some cases of broken filenames\">url-decode",
	"frt_rst": "reset modified filenames back to the original ones\">↺ reset",
	"frt_abrt": "abort and close this window\">❌ cancel",
	"frb_apply": "APPLY RENAME",
	"fr_adv": "batch / metadata / pattern renaming\">advanced",
	"fr_case": "case-sensitive regex\">case",
	"fr_win": "windows-safe names; replace <code>&lt;&gt;:&quot;\\|?*</code> with japanese fullwidth characters\">win",
	"fr_slash": "replace <code>/</code> with a character that doesn't cause new folders to be created\">no /",
	"fr_re": "regex search pattern to apply to original filenames; capturing groups can be referenced in the format field below like &lt;code&gt;(1)&lt;/code&gt; and &lt;code&gt;(2)&lt;/code&gt; and so on",
	"fr_fmt": "inspired by foobar2000:$N&lt;code&gt;(title)&lt;/code&gt; is replaced by song title,$N&lt;code&gt;[(artist) - ](title)&lt;/code&gt; skips [this] part if artist is blank$N&lt;code&gt;$lpad((tn),2,0)&lt;/code&gt; pads tracknumber to 2 digits",
	"fr_pdel": "delete",
	"fr_pnew": "save as",
	"fr_pname": "provide a name for your new preset",
	"fr_aborted": "aborted",
	"fr_lold": "old name",
	"fr_lnew": "new name",
	"fr_tags": "tags for the selected files (read-only, just for reference):",
	"fr_busy": "renaming {0} items...\n\n{1}",
	"fr_efail": "rename failed:\n",
	"fr_nchg": "{0} of the new names were altered due to <code>win</code> and/or <code>no /</code>\n\nOK to continue with these altered new names?",

	"fd_ok": "delete OK",
	"fd_err": "delete failed:\n",
	"fd_none": "nothing was deleted; maybe blocked by server config (xbd)?",
	"fd_busy": "deleting {0} items...\n\n{1}",
	"fd_warn1": "DELETE these {0} items?",
	"fd_warn2": "<b>Last chance!</b> No way to undo. Delete?",

	"fc_ok": "cut {0} items",
	"fc_warn": 'cut {0} items\n\nbut: only <b>this</b> browser-tab can paste them\n(since the selection is so absolutely massive)',

	"fcc_ok": "copied {0} items to bảng nhớ tạm",
	"fcc_warn": 'copied {0} items to bảng nhớ tạm\n\nbut: only <b>this</b> browser-tab can paste them\n(since the selection is so absolutely massive)',

	"fp_apply": "use these names",
	"fp_ecut": "first cut or copy some files / folders to paste / move\n\nnote: you can cut / paste across different browser tabs",
	"fp_ename": "{0} items cannot be moved here because the names are already taken. Give them new names below to continue, or blank the name to skip them:",
	"fcp_ename": "{0} items cannot be copied here because the names are already taken. Give them new names below to continue, or blank the name to skip them:",
	"fp_emore": "there are still some filename collisions left to fix",
	"fp_ok": "move OK",
	"fcp_ok": "copy OK",
	"fp_busy": "moving {0} items...\n\n{1}",
	"fcp_busy": "copying {0} items...\n\n{1}",
	"fp_abrt": "aborting...",
	"fp_err": "move failed:\n",
	"fcp_err": "copy failed:\n",
	"fp_confirm": "move these {0} items here?",
	"fcp_confirm": "copy these {0} items here?",
	"fp_etab": 'failed to read bảng nhớ tạm from other browser tab',
	"fp_name": "uploading a file from your device. Give it a name:",
	"fp_both_m": '<h6>choose what to paste</h6><code>Enter</code> = Move {0} files from «{1}»\n<code>ESC</code> = Upload {2} files from your device',
	"fcp_both_m": '<h6>choose what to paste</h6><code>Enter</code> = Copy {0} files from «{1}»\n<code>ESC</code> = Upload {2} files from your device',
	"fp_both_b": '<a href="#" id="modal-ok">Move</a><a href="#" id="modal-ng">Upload</a>',
	"fcp_both_b": '<a href="#" id="modal-ok">Copy</a><a href="#" id="modal-ng">Upload</a>',

	"mk_noname": "type a name into the text field on the left before you do that :p",
	"nmd_i1": "also add the file extension you want, for example <code>.md</code>",
	"nmd_i2": "you can only create <code>.md</code> files because you don't have the delete-permission",

	"tv_load": "Loading text document:\n\n{0}\n\n{1}% ({2} of {3} MiB loaded)",
	"tv_xe1": "could not load textfile:\n\nerror ",
	"tv_xe2": "404, file not found",
	"tv_lst": "list of textfiles in",
	"tvt_close": "return to folder view$NPhím tắt: M (or Esc)\">❌ close",
	"tvt_dl": "download this file$NPhím tắt: Y\">💾 download",
	"tvt_prev": "show previous document$NPhím tắt: i\">⬆ prev",
	"tvt_next": "show next document$NPhím tắt: K\">⬇ next",
	"tvt_sel": "select file &nbsp; ( for cut / copy / delete / ... )$NPhím tắt: S\">sel",
	"tvt_edit": "open file in text editor$NPhím tắt: E\">✏️ edit",
	"tvt_tail": "monitor file for changes; show new lines in real time\">📡 follow",
	"tvt_wrap": "word-wrap\">↵",
	"tvt_atail": "lock scroll to bottom of page\">⚓",
	"tvt_ctail": "decode terminal colors (ansi escape codes)\">🌈",
	"tvt_ntail": "scrollback limit (how many bytes of text to keep loaded)",

	"m3u_add1": "song added to m3u playlist",
	"m3u_addn": "{0} songs added to m3u playlist",
	"m3u_clip": "m3u playlist now copied to bảng nhớ tạm\n\nyou should create a new textfile named something.m3u and paste the playlist in that document; this will make it playable",

	"gt_vau": "don't show videos, just play the audio\">🎧",
	"gt_msel": "enable file selection; ctrl-click a file to override$N$N&lt;em&gt;when active: doubleclick a file / folder to open it&lt;/em&gt;$N$NPhím tắt: S\">multiselect",
	"gt_crop": "center-crop thumbnails\">crop",
	"gt_3x": "hi-res thumbnails\">3x",
	"gt_zoom": "zoom",
	"gt_chop": "chop",
	"gt_sort": "sort by",
	"gt_name": "name",
	"gt_sz": "size",
	"gt_ts": "date",
	"gt_ext": "type",
	"gt_c1": "truncate filenames more (show less)",
	"gt_c2": "truncate filenames less (show more)",

	"sm_w8": "searching...",
	"sm_prev": "search results below are from a previous query:\n  ",
	"sl_close": "close search results",
	"sl_hits": "showing {0} hits",
	"sl_moar": "load more",

	"s_sz": "size",
	"s_dt": "date",
	"s_rd": "path",
	"s_fn": "name",
	"s_ta": "tags",
	"s_ua": "up@",
	"s_ad": "adv.",
	"s_s1": "minimum MiB",
	"s_s2": "maximum MiB",
	"s_d1": "min. iso8601",
	"s_d2": "max. iso8601",
	"s_u1": "uploaded after",
	"s_u2": "and/or before",
	"s_r1": "path contains &nbsp; (space-separated)",
	"s_f1": "name contains &nbsp; (negate with -nope)",
	"s_t1": "tags contains &nbsp; (^=start, end=$)",
	"s_a1": "specific metadata properties",

	"md_eshow": "cannot render ",
	"md_off": "[📜<em>readme</em>] disabled in [⚙️] -- document hidden",

	"badreply": "Failed to parse reply from server",

	"xhr403": "403: Access denied\n\ntry pressing F5, maybe you got logged out",
	"xhr0": "unknown (probably lost connection to server, or server is offline)",
	"cf_ok": "sorry about that -- DD" + wah + "oS protection kicked in\n\nthings should resume in about 30 sec\n\nif nothing happens, hit F5 to reload the page",
	"tl_xe1": "could not list subfolders:\n\nerror ",
	"tl_xe2": "404: Folder not found",
	"fl_xe1": "could not list files in folder:\n\nerror ",
	"fl_xe2": "404: Folder not found",
	"fd_xe1": "could not create subfolder:\n\nerror ",
	"fd_xe2": "404: Parent folder not found",
	"fsm_xe1": "could not send message:\n\nerror ",
	"fsm_xe2": "404: Parent folder not found",
	"fu_xe1": "failed to load unpost list from server:\n\nerror ",
	"fu_xe2": "404: File not found??",

	"fz_tar": "uncompressed gnu-tar file (linux / mac)",
	"fz_pax": "uncompressed pax-format tar (slower)",
	"fz_targz": "gnu-tar with gzip level 3 compression$N$Nthis is usually very slow, so$Nuse uncompressed tar instead",
	"fz_tarxz": "gnu-tar with xz level 1 compression$N$Nthis is usually very slow, so$Nuse uncompressed tar instead",
	"fz_zip8": "zip with utf8 filenames (maybe wonky on windows 7 and older)",
	"fz_zipd": "zip with traditional cp437 filenames, for really old software",
	"fz_zipc": "cp437 with crc32 computed early,$Nfor MS-DOS PKZIP v2.04g (october 1993)$N(takes longer to process before download can start)",

	"un_m1": "you can delete your recent uploads (or abort unfinished ones) below",
	"un_upd": "refresh",
	"un_m4": "or share the files visible below:",
	"un_ulist": "show",
	"un_ucopy": "copy",
	"un_flt": "optional filter:&nbsp; URL must contain",
	"un_fclr": "clear filter",
	"un_derr": 'unpost-delete failed:\n',
	"un_f5": 'something broke, please try a refresh or hit F5',
	"un_uf5": "sorry but you have to refresh the page (for example by pressing F5 or CTRL-R) before this upload can be aborted",
	"un_nou": '<b>warning:</b> server too busy to show unfinished uploads; click the "refresh" link in a bit',
	"un_noc": '<b>warning:</b> unpost of fully uploaded files is not enabled/permitted in server config',
	"un_max": "showing first 2000 files (use the filter)",
	"un_avail": "{0} recent uploads can be deleted<br />{1} unfinished ones can be aborted",
	"un_m2": "sorted by upload time; most recent first:",
	"un_no1": "sike! no uploads are sufficiently recent",
	"un_no2": "sike! no uploads matching that filter are sufficiently recent",
	"un_next": "delete the next {0} files below",
	"un_abrt": "abort",
	"un_del": "delete",
	"un_m3": "loading your recent uploads...",
	"un_busy": "deleting {0} files...",
	"un_clip": "{0} links copied to bảng nhớ tạm",

	"u_https1": "you should",
	"u_https2": "switch to https",
	"u_https3": "for better performance",
	"u_ancient": 'your browser is impressively ancient -- maybe you should <a href="#" onclick="goto(\'bup\')">use bup instead</a>',
	"u_nowork": "need firefox 53+ or chrome 57+ or iOS 11+",
	"tail_2old": "need firefox 105+ or chrome 71+ or iOS 14.5+",
	"u_nodrop": 'your browser is too old for drag-and-drop uploading',
	"u_notdir": "that's not a folder!\n\nyour browser is too old,\nplease try dragdrop instead",
	"u_uri": "to dragdrop images from other browser windows,\nplease drop it onto the big upload button",
	"u_enpot": 'switch to <a href="#">potato UI</a> (may improve upload speed)',
	"u_depot": 'switch to <a href="#">fancy UI</a> (may reduce upload speed)',
	"u_gotpot": 'switching to the potato UI for improved upload speed,\n\nfeel free to disagree and switch back!',
	"u_pott": "<p>files: &nbsp; <b>{0}</b> finished, &nbsp; <b>{1}</b> failed, &nbsp; <b>{2}</b> busy, &nbsp; <b>{3}</b> queued</p>",
	"u_ever": "this is the basic uploader; up2k needs at least<br>chrome 21 // firefox 13 // edge 12 // opera 12 // safari 5.1",
	"u_su2k": 'this is the basic uploader; <a href="#" id="u2yea">up2k</a> is better',
	"u_uput": 'optimize for speed (skip checksum)',
	"u_ewrite": 'you do not have write-access to this folder',
	"u_eread": 'you do not have read-access to this folder',
	"u_enoi": 'file-search is not enabled in server config',
	"u_enoow": "overwrite will not work here; need Delete-permission",
	"u_badf": 'These {0} files (of {1} total) were skipped, possibly due to filesystem permissions:\n\n',
	"u_blankf": 'These {0} files (of {1} total) are blank / empty; upload them anyways?\n\n',
	"u_applef": 'These {0} files (of {1} total) are probably undesirable;\nPress <code>OK/Enter</code> to SKIP the following files,\nPress <code>Cancel/ESC</code> to NOT exclude, and UPLOAD those as well:\n\n',
	"u_just1": '\nMaybe it works better if you select just one file',
	"u_ff_many": "if you're using <b>Linux / MacOS / Android,</b> then this amount of files <a href=\"https://bugzilla.mozilla.org/show_bug.cgi?id=1790500\" target=\"_blank\"><em>may</em> crash Firefox!</a>\nif that happens, please try again (or use Chrome).",
	"u_up_life": "This upload will be deleted from the server\n{0} after it completes",
	"u_asku": 'upload these {0} files to <code>{1}</code>',
	"u_unpt": "you can undo / delete this upload using the top-left 🧯",
	"u_bigtab": 'about to show {0} files\n\nthis may crash your browser, are you sure?',
	"u_scan": 'Scanning files...',
	"u_dirstuck": 'directory iterator got stuck trying to access the following {0} items; will skip:',
	"u_etadone": 'Done ({0}, {1} files)',
	"u_etaprep": '(preparing to upload)',
	"u_hashdone": 'hashing done',
	"u_hashing": 'hash',
	"u_hs": 'handshaking...',
	"u_started": "the files are now being uploaded; see [🚀]",
	"u_dupdefer": "duplicate; will be processed after all other files",
	"u_actx": "click this text to prevent loss of<br />performance when switching to other windows/tabs",
	"u_fixed": "OK!&nbsp; Fixed it 👍",
	"u_cuerr": "failed to upload chunk {0} of {1};\nprobably harmless, continuing\n\nfile: {2}",
	"u_cuerr2": "server rejected upload (chunk {0} of {1});\nwill retry later\n\nfile: {2}\n\nerror ",
	"u_ehstmp": "will retry; see bottom-right",
	"u_ehsfin": "server rejected the request to finalize upload; retrying...",
	"u_ehssrch": "server rejected the request to perform search; retrying...",
	"u_ehsinit": "server rejected the request to initiate upload; retrying...",
	"u_eneths": "network error while performing upload handshake; retrying...",
	"u_enethd": "network error while testing target existence; retrying...",
	"u_cbusy": "waiting for server to trust us again after a network glitch...",
	"u_ehsdf": "server ran out of disk space!\n\nwill keep retrying, in case someone\nfrees up enough space to continue",
	"u_emtleak1": "it looks like your webbrowser may have a memory leak;\nplease",
	"u_emtleak2": ' <a href="{0}">switch to https (recommended)</a> or ',
	"u_emtleak3": ' ',
	"u_emtleakc": 'try the following:\n<ul><li>hit <code>F5</code> to refresh the page</li><li>then disable the &nbsp;<code>mt</code>&nbsp; button in the &nbsp;<code>⚙️ settings</code></li><li>and try that upload again</li></ul>Uploads will be a bit slower, but oh well.\nSorry for the trouble !\n\nPS: chrome v107 <a href="https://bugs.chromium.org/p/chromium/issues/detail?id=1354816" target="_blank">has a bugfix</a> for this',
	"u_emtleakf": 'try the following:\n<ul><li>hit <code>F5</code> to refresh the page</li><li>then enable <code>🥔</code> (potato) in the upload UI<li>and try that upload again</li></ul>\nPS: firefox <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1790500" target="_blank">will hopefully have a bugfix</a> at some point',
	"u_s404": "not found on server",
	"u_expl": "explain",
	"u_maxconn": "most browsers limit this to 6, but firefox lets you raise it with <code>connections-per-server</code> in <code>about:config</code>",
	"u_tu": '<p class="warn">WARNING: turbo enabled, <span>&nbsp;client may not detect and resume incomplete uploads; see turbo-button tooltip</span></p>',
	"u_ts": '<p class="warn">WARNING: turbo enabled, <span>&nbsp;search results can be incorrect; see turbo-button tooltip</span></p>',
	"u_turbo_c": "turbo is disabled in server config",
	"u_turbo_g": "disabling turbo because you don't have\ndirectory listing privileges within this volume",
	"u_life_cfg": 'autodelete after <input id="lifem" p="60" /> min (or <input id="lifeh" p="3600" /> hours)',
	"u_life_est": 'upload will be deleted <span id="lifew" tt="local time">---</span>',
	"u_life_max": 'this folder enforces a\nmax lifetime of {0}',
	"u_unp_ok": 'unpost is allowed for {0}',
	"u_unp_ng": 'unpost will NOT be allowed',
	"ue_ro": 'your access to this folder is Read-Only\n\n',
	"ue_nl": 'you are currently not logged in',
	"ue_la": 'you are currently logged in as "{0}"',
	"ue_sr": 'you are currently in file-search mode\n\nswitch to upload-mode by clicking the magnifying glass 🔎 (next to the big SEARCH button), and try uploading again\n\nsorry',
	"ue_ta": 'try uploading again, it should work now',
	"ue_ab": "this file is already being uploaded into another folder, and that upload must be completed before the file can be uploaded elsewhere.\n\nYou can abort and forget the initial upload using the top-left 🧯",
	"ur_1uo": "OK: File uploaded successfully",
	"ur_auo": "OK: All {0} files uploaded successfully",
	"ur_1so": "OK: File found on server",
	"ur_aso": "OK: All {0} files found on server",
	"ur_1un": "Upload failed, sorry",
	"ur_aun": "All {0} uploads failed, sorry",
	"ur_1sn": "File was NOT found on server",
	"ur_asn": "The {0} files were NOT found on server",
	"ur_um": "Finished;\n{0} uploads OK,\n{1} uploads failed, sorry",
	"ur_sm": "Finished;\n{0} files found on server,\n{1} files NOT found on server",

	"lang_set": "refresh to make the change take effect?",

	"splash": {
		"a1": "refresh",
		"b1": "howdy stranger &nbsp; <small>(you're not logged in)</small>",
		"c1": "logout",
		"d1": "dump stack",  // TLNote: "d2" is the tooltip for this button
		"d2": "shows the state of all active threads",
		"e1": "reload cfg",
		"e2": "reload config files (accounts/volumes/volflags),$Nand rescan all e2ds volumes$N$Nnote: any changes to global settings$Nrequire a full restart to take effect",
		"f1": "you can browse:",
		"g1": "you can upload to:",
		"cc1": "other stuff:",
		"h1": "disable k304",  // TLNote: "j1" explains what k304 is
		"i1": "enable k304",
		"j1": "enabling k304 will disconnect your client on every HTTP 304, which can prevent some buggy proxies from getting stuck (suddenly not loading pages), <em>but</em> it will also make things slower in general",
		"k1": "reset client settings",
		"l1": "login for more:",
		"m1": "welcome back,",  // TLNote: "welcome back, USERNAME"
		"n1": "404 not found &nbsp;┐( ´ -`)┌",
		"o1": 'or maybe you don\'t have access -- try a password or <a href="' + SR + '/?h">go home</a>',
		"p1": "403 forbiddena &nbsp;~┻━┻",
		"q1": 'use a password or <a href="' + SR + '/?h">go home</a>',
		"r1": "go home",
		".s1": "rescan",
		"t1": "action",  // TLNote: this is the header above the "rescan" buttons
		"u2": "time since the last server write$N( upload / rename / ... )$N$N17d = 17 days$N1h23 = 1 hour 23 minutes$N4m56 = 4 minutes 56 seconds",
		"v1": "connect",
		"v2": "use this server as a local HDD",
		"w1": "switch to https",
		"x1": "change password",
		"y1": "edit shares",  // TLNote: shows the list of folders that the user has decided to share
		"z1": "unlock this share:",  // TLNote: the password prompt to see a hidden share
		"ta1": "fill in your new password first",
		"ta2": "repeat to confirm new password:",
		"ta3": "found a typo; please try again",
		"aa1": "incoming files:",
		"ab1": "disable no304",
		"ac1": "enable no304",
		"ad1": "enabling no304 will disable all caching; try this if k304 wasn't enough. This will waste a huge amount of network traffic!",
		"ae1": "active downloads:",
		"af1": "show recent uploads",
	}
};
