FROM    alpine:latest
WORKDIR /z

RUN     apk --no-cache add \
            wget \
            py3-pillow \
            ffmpeg \
        && mkdir /cfg /w \
        && chmod 777 /cfg /w \
        && echo % /cfg > initcfg

COPY    i/dist/copyparty-sfx.py ./
WORKDIR /w
ENTRYPOINT ["python3", "/z/copyparty-sfx.py", "-c", "/z/initcfg"]
