# not actually YAML but lets pretend:
# -*- mode: yaml -*-
# vim: ft=yaml:


[global]
  # general settings
  name: collabora-example    # name displayed in web ui
  ansi                       # enable colors in log messages (both in logfiles and stdout)
  usernames                  # require usernames to authenticate

  # Filesystem and media indexing
  e2dsa                      # enable file indexing and filesystem scanning
  e2ts                       # enable multimedia indexing

  # set up WOPI
  wopi                       # enable WOPI (collabora)
  wopi-url: https://office.example.org/ # collabora instance address

  # set up XFF
  xff-hdr: x-forwarded-for   # X-Forwarded-For header set by reverse proxy
  xff-src: 10.0.10.0/24      # trust x-forwarded-for header for requests coming from `copyparty` docker network
  rproxy: 1                  # which ip to associate clients with; [0]=tcp, [1]=origin (first x-fwd, unsafe), [2]=outermost-proxy, [3]=second-proxy, [-1]=closest-proxy

  # disable https – let reverse proxy handle it
  no-crt
  http-only

  # filesystem security checks; read https://copyparty.eu/cli/#ls-help-page
  ls: *,*,ln,p,r

[accounts]
  test_user:test_password

[/]
  /w
  accs:
    A: test_user
