# note: copied from copyparty/docs/examples/docker/basic-docker-compose/copyparty.conf
# not actually YAML but lets pretend:
# -*- mode: yaml -*-
# vim: ft=yaml:


[global]
  e2dsa  # enable file indexing and filesystem scanning
  e2ts   # enable multimedia indexing
  ansi   # enable colors in log messages (both in logfiles and stdout)

  # q, lo: /cfg/log/%Y-%m%d.log   # log to file instead of docker

  # p: 3939          # listen on another port
  # ipa: 10.89.      # only allow connections from 10.89.*
  # ipa: 172.16.4.0/23  # ...or only 172.16.4.* and 172.16.5.*
  # ipa: lan         # ...or allow LAN only; reject internet IPs
  # df: 16           # stop accepting uploads if less than 16 GB free disk space
  # ver              # show copyparty version in the controlpanel
  # grid             # show thumbnails/grid-view by default
  # theme: 2         # monokai
  # name: datasaver  # change the server-name that's displayed in the browser
  # stats, nos-dup   # enable the prometheus endpoint, but disable the dupes counter (too slow)
  # no-robots, force-js  # make it harder for search engines to read your server

  # enable version-checking by uncommenting one of the vc-url lines below;
  # shows a warning-banner in the controlpanel if your version has a known vulnerability
  #vc-url: https://api.github.com/repos/9001/copyparty/security-advisories?per_page=9
  #vc-url: https://api.copyparty.eu/advisories
  vc-exit  # panic and shutdown instead of just showing the warning


[accounts]
  ed: wark  # username: password


[/]            # create a volume at "/" (the webroot), which will
  /w           # share /w (the docker data volume)
  accs:
    rw: *      # everyone gets read-write access, but
    rwmda: ed  # the user "ed" gets read-write-move-delete-admin
  flags:
    e2ds       # enable filesystem-scanning for this volume only
