# not actually YAML but lets pretend:
# -*- mode: yaml -*-
# vim: ft=yaml:


[global]
  e2dsa  # enable file indexing and filesystem scanning
  e2ts   # enable multimedia indexing
  ansi   # enable colors in log messages (both in logfiles and stdout)

  # If using a reverse proxy: 
   rproxy: -1                  # Tell cpp we are behind 1 proxy
   xff-src: 10.0.0.0/8         # Trust connections from Docker Gateway (10.0.2.1)
  # If also using cloudflare DNS with proxy:   (also keep the 2 configs above enabled/uncommented!) 
  # (see a full working nginx file example to use domain name + https + cloudflare in docs/examples/docker/basic-docker-compose)
  # xff-hdr: x-forwarded-for     # Read the real IP from this header


  # q, lo: /cfg/log/%Y-%m%d.log   # log to file instead of docker

  # p: 3939          # listen on another port
  # ipa: 10.89.      # only allow connections from 10.89.*
  # ipa: 172.16.4.0/23  # ...or only 172.16.4.* and 172.16.5.*
  # ipa: lan         # ...or allow LAN only; reject internet IPs
  # df: 16           # stop accepting uploads if less than 16 GB free disk space
  # ver              # show copyparty version in the controlpanel
  # grid             # show thumbnails/grid-view by default
  # theme: 2         # monokai
  # name: datasaver  # change the server-name that's displayed in the browser
  # stats, nos-dup   # enable the prometheus endpoint, but disable the dupes counter (too slow)
  # no-robots, force-js  # make it harder for search engines to read your server


[accounts]
  ed: wark  # username: password


[/]            # create a volume at "/" (the webroot), which will
  /w           # share /w (the docker data volume)
  accs:
    rw: *      # everyone gets read-write access, but
    rwmda: ed  # the user "ed" gets read-write-move-delete-admin
